const express = require('express');
const upload = require('../middlewares/fileUpload'); // Multer setup
const File = require('../models/File');

const router = express.Router();

router.get('/', (req, res) => res.render('upload'))

// Handle file upload and save metadata to MongoDB
router.post('/', upload.single('document'), async (req, res) => {
  try {
    // Use the custom file name if provided, otherwise use the original file name
    let fileName = req.body.customFileName || req.file.originalname;
    fileName = fileName.replace(/\s+/g, '_');
    // Create a new document with file metadata
    const newFile = new File({
      originalName: fileName,
      storedName: req.file.filename, // Name generated by Multer
      filePath: req.file.path, // Path to the uploaded file on the server
      description: req.body.description,
      year: req.body.year,
      subject: req.body.subject,
      subjectCode: req.body.subjectCode,
      type: req.body.type
    });

    // Save the metadata to MongoDB
    await newFile.save();

    // Respond with success message
    res.render('uploadSuccess');
  } catch (error) {
    console.error('File upload error:', error);
    res.status(500).send(error.message);
  }
});
module.exports = router;